### ISSUE TITLE
encoding : null on RaspberryPi

### ISSUE THREAD

**Issue by TigerChi** [Lellansin/node-scanf#12]
When I use node-scanf on RaspberryPi, has some problem as below.
And solve by modify node-scanf/lib/gets.js : 43
from
`var content = buf.toString(null, 0, bytesRead - 1);`
to
`var content = buf.toString('ascii', 0, bytesRead - 1);`

> buffer.js:557
  throw new TypeError('Unknown encoding: ' + encoding);
  ^

TypeError: Unknown encoding: null
    at stringSlice (buffer.js:557:9)
    at Buffer.toString (buffer.js:593:10)
    at module.exports (/home/pi/kd/node_modules/scanf/lib/gets.js:43:21)
    at getInput (/home/pi/kd/node_modules/scanf/lib/scanf.js:64:15)
    at getLine (/home/pi/kd/node_modules/scanf/lib/scanf.js:138:14)
    at dealType (/home/pi/kd/node_modules/scanf/lib/scanf.js:169:13)
    at module.exports (/home/pi/kd/node_modules/scanf/lib/scanf.js:31:12)
    at enterKey (/home/pi/kd/vig.js:54:8)
    at MyInput (/home/pi/kd/vig.js:47:2)
    at Object.<anonymous> (/home/pi/kd/vig.js:81:1)

**Comment by TigerChi** [comment]
I find #11 resolve this problem, but when I use 
`npm install scanf` 
still download old version.

**Comment by Lellansin** [comment]
Um, sorry for reply later, I'v fixed it by republishing the NPM. you can renew it by npm install the new version.

Feel free to reopen.

**Comment by TigerChi** [comment]
Thanks for reply :)
